### ISSUE TITLE
Issues starting new distro with uAAL already installed

### ISSUE THREAD

**Issue by Alfiva** [universAAL/distro.karaf#2]
After the update in which the distro is already configured to run uAAL off-the-shelf, the instructions in the quick developer guide become, let's say "overridden" rather than "obsolete", since they tell to "features:install uAAL-Basic.Coordinator".
That is not the issue though. Instructions can be edited. The issue is that, if you do install that feature, you get the following error, as if the OSGi service tracker was not installed:

java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/osgi/util/tracker/ServiceTracker
        at org.universAAL.middleware.container.osgi.run.uAALBundleExtender.bundleChanged(uAALBundleExtender.java:174)
...

But I noticed 2 thigs:
-If you try to type in commands (e.g. list or feature:list) when Karaf is started, you may get error messages saying those commands are not available. After quite a while (I assume when uAAL is finally started), the commands seem to become available.
-After the error, if you close Karaf and then restart, the uAAL-Basic.Coordinator feature "seems" to be already installed, and everything seems to work OK.

So my questions is if I am missing something now that uAAL is started by default, or if maybe there is something wrong with features, orders, or the uAAL-Basic.Coordinator in particular.

**Comment by amedranogil** [comment]
yes, I have come before with the same issue; and exactly the same experiments with the same results.

From the research I have done it seems to be related to the service gateway component, which susbcribes to OSGi services implementing the HttpService (If I am not mistakent) service. The problem seems to be that somehow the ServiceTracker is not loaded when this happens (yes I got to the same conclusion as you did). 
But here comes the good part: org.osgi.util.tracker.ServiceTracker is exported by the bundle with start level 0, yes the core of OSGi container itself.
I haven't figured out yet why this happens, but again as you have observed if started again it is not an issue.

There have already been some attempts at solving this issue ( see https://github.com/universAAL/middleware/commit/500b3b5075c2c508ea0a00d88e3cef85a450982a ). It seems that the classloader used is not the service gateway's bundle classloader but the container.osgi component. This should only happen in the case of a ModuleActivator kind of module, whereas the service gateway has the BundleActivator kind (not generic container).
So the question is why is this happening? maybe I tried to generalise the component and deployed it, forgot I did that and now the version being used is this type of container. But after checking the nexus this does not seem to be the case.

So the problem seems to be in the way uAALBundleExtender manages bundles, it is not just handling the bundles it is supposed to manage (the ModuleActivator kind) but all of them. I don't really know how this works because this class was introduced by Marek (although I am in deed a big fan of using ModuleActivator).
If you get to see this error again, please copy the full exception stack to see when exactly it is attempting to start the bundle.

**Comment by Alfiva** [comment]
Here the stacktrace 
[stacktrace.txt](https://github.com/universAAL/distro.karaf/files/664040/stacktrace.txt)

**Comment by amedranogil** [comment]
can you reliably reproduce the bug? if so how?

**Comment by amedranogil** [comment]
Added Commit https://github.com/universAAL/middleware/commit/4fc7deaae6b8bc2832569488340a5b3ab3a7afb5
Test if this solves the issue. Make sure all bundles are started (this modification may cause some bundles that should start, not to start).

**Comment by Alfiva** [comment]
Good, looks like it works.
This is the procedure I followed, anyway:
1-Download distro.karaf (checkout or zip) from GitHub, branch 3.0.5
2-Unzip and run Karaf.bat (in Windows)
3-Wait for the typical GMS messages to signal that uAAL has started
4-Type command "feature:install uAAL-Basic.Coordinator"
5- Get error
It was consistent and repeatable (starting every time from scratch, a blank Karaf distro, not restarting). Now with the fix, following those steps, the error is gone and it all goes smooth.
